package shoes.entity;
// Generated Oct 2, 2019 5:01:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private int billId;
     private Users users;
     private Date created;
     private Double totalaman;
     private Set billretails = new HashSet(0);

    public Bill() {
    }

	
    public Bill(int billId, Date created) {
        this.billId = billId;
        this.created = created;
    }
    public Bill(int billId, Users users, Date created, Double totalaman, Set billretails) {
       this.billId = billId;
       this.users = users;
       this.created = created;
       this.totalaman = totalaman;
       this.billretails = billretails;
    }
   
    public int getBillId() {
        return this.billId;
    }
    
    public void setBillId(int billId) {
        this.billId = billId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Double getTotalaman() {
        return this.totalaman;
    }
    
    public void setTotalaman(Double totalaman) {
        this.totalaman = totalaman;
    }
    public Set getBillretails() {
        return this.billretails;
    }
    
    public void setBillretails(Set billretails) {
        this.billretails = billretails;
    }




}


