package shoes.entity;
// Generated Oct 2, 2019 5:01:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private int colorId;
     private String colorName;
     private Set products = new HashSet(0);

    public Color() {
    }

	
    public Color(int colorId, String colorName) {
        this.colorId = colorId;
        this.colorName = colorName;
    }
    public Color(int colorId, String colorName, Set products) {
       this.colorId = colorId;
       this.colorName = colorName;
       this.products = products;
    }
   
    public int getColorId() {
        return this.colorId;
    }
    
    public void setColorId(int colorId) {
        this.colorId = colorId;
    }
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


