package shoes.entity;
// Generated Oct 2, 2019 5:01:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Img generated by hbm2java
 */
public class Img  implements java.io.Serializable {


     private int imgId;
     private Product product;
     private Slide slide;
     private String imgName;
     private String imglink;

    public Img() {
    }

	
    public Img(int imgId) {
        this.imgId = imgId;
    }
    public Img(int imgId, Product product, Slide slide, String imgName, String imglink) {
       this.imgId = imgId;
       this.product = product;
       this.slide = slide;
       this.imgName = imgName;
       this.imglink = imglink;
    }
   
    public int getImgId() {
        return this.imgId;
    }
    
    public void setImgId(int imgId) {
        this.imgId = imgId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Slide getSlide() {
        return this.slide;
    }
    
    public void setSlide(Slide slide) {
        this.slide = slide;
    }
    public String getImgName() {
        return this.imgName;
    }
    
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }
    public String getImglink() {
        return this.imglink;
    }
    
    public void setImglink(String imglink) {
        this.imglink = imglink;
    }




}


