package shoes.entity;
// Generated Oct 2, 2019 5:01:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int productId;
     private Categorios categorios;
     private Color color;
     private Size size;
     private String productName;
     private String materia;
     private double price;
     private Integer buy;
     private Integer productView;
     private Date created;
     private Integer discount;
     private String productDescription;
     private String imgLink;
     private Set billretails = new HashSet(0);
     private Set imgs = new HashSet(0);

    public Product() {
    }

	
    public Product(int productId, String productName, String materia, double price, Date created) {
        this.productId = productId;
        this.productName = productName;
        this.materia = materia;
        this.price = price;
        this.created = created;
    }
    public Product(int productId, Categorios categorios, Color color, Size size, String productName, String materia, double price, Integer buy, Integer productView, Date created, Integer discount, String productDescription, String imgLink, Set billretails, Set imgs) {
       this.productId = productId;
       this.categorios = categorios;
       this.color = color;
       this.size = size;
       this.productName = productName;
       this.materia = materia;
       this.price = price;
       this.buy = buy;
       this.productView = productView;
       this.created = created;
       this.discount = discount;
       this.productDescription = productDescription;
       this.imgLink = imgLink;
       this.billretails = billretails;
       this.imgs = imgs;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Categorios getCategorios() {
        return this.categorios;
    }
    
    public void setCategorios(Categorios categorios) {
        this.categorios = categorios;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Size getSize() {
        return this.size;
    }
    
    public void setSize(Size size) {
        this.size = size;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Integer getBuy() {
        return this.buy;
    }
    
    public void setBuy(Integer buy) {
        this.buy = buy;
    }
    public Integer getProductView() {
        return this.productView;
    }
    
    public void setProductView(Integer productView) {
        this.productView = productView;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public String getImgLink() {
        return this.imgLink;
    }
    
    public void setImgLink(String imgLink) {
        this.imgLink = imgLink;
    }
    public Set getBillretails() {
        return this.billretails;
    }
    
    public void setBillretails(Set billretails) {
        this.billretails = billretails;
    }
    public Set getImgs() {
        return this.imgs;
    }
    
    public void setImgs(Set imgs) {
        this.imgs = imgs;
    }




}


