package shoes.entity;
// Generated Oct 2, 2019 5:01:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Size generated by hbm2java
 */
public class Size  implements java.io.Serializable {


     private int sizeId;
     private double sizeNumber;
     private Set products = new HashSet(0);

    public Size() {
    }

	
    public Size(int sizeId, double sizeNumber) {
        this.sizeId = sizeId;
        this.sizeNumber = sizeNumber;
    }
    public Size(int sizeId, double sizeNumber, Set products) {
       this.sizeId = sizeId;
       this.sizeNumber = sizeNumber;
       this.products = products;
    }
   
    public int getSizeId() {
        return this.sizeId;
    }
    
    public void setSizeId(int sizeId) {
        this.sizeId = sizeId;
    }
    public double getSizeNumber() {
        return this.sizeNumber;
    }
    
    public void setSizeNumber(double sizeNumber) {
        this.sizeNumber = sizeNumber;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


