package shoes.entity;
// Generated Oct 2, 2019 5:01:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Slide generated by hbm2java
 */
public class Slide  implements java.io.Serializable {


     private int slideId;
     private String conten;
     private Set imgs = new HashSet(0);

    public Slide() {
    }

	
    public Slide(int slideId, String conten) {
        this.slideId = slideId;
        this.conten = conten;
    }
    public Slide(int slideId, String conten, Set imgs) {
       this.slideId = slideId;
       this.conten = conten;
       this.imgs = imgs;
    }
   
    public int getSlideId() {
        return this.slideId;
    }
    
    public void setSlideId(int slideId) {
        this.slideId = slideId;
    }
    public String getConten() {
        return this.conten;
    }
    
    public void setConten(String conten) {
        this.conten = conten;
    }
    public Set getImgs() {
        return this.imgs;
    }
    
    public void setImgs(Set imgs) {
        this.imgs = imgs;
    }




}


