package shoes.entity;
// Generated Oct 2, 2019 5:01:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private String username;
     private String userpass;
     private String gioitinh;
     private String diachi;
     private Integer nhomquyen;
     private String sdt;
     private String email;
     private Set bills = new HashSet(0);

    public Users() {
    }

	
    public Users(int userId, String username, String userpass) {
        this.userId = userId;
        this.username = username;
        this.userpass = userpass;
    }
    public Users(int userId, String username, String userpass, String gioitinh, String diachi, Integer nhomquyen, String sdt, String email, Set bills) {
       this.userId = userId;
       this.username = username;
       this.userpass = userpass;
       this.gioitinh = gioitinh;
       this.diachi = diachi;
       this.nhomquyen = nhomquyen;
       this.sdt = sdt;
       this.email = email;
       this.bills = bills;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUserpass() {
        return this.userpass;
    }
    
    public void setUserpass(String userpass) {
        this.userpass = userpass;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public Integer getNhomquyen() {
        return this.nhomquyen;
    }
    
    public void setNhomquyen(Integer nhomquyen) {
        this.nhomquyen = nhomquyen;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getBills() {
        return this.bills;
    }
    
    public void setBills(Set bills) {
        this.bills = bills;
    }




}


